apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-depl
  namespace: krypton
  labels:
    app: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: 411941102530.dkr.ecr.us-west-1.amazonaws.com/portal:---TAG---
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service-cluster-ip
  namespace: krypton
spec:
  type: ClusterIP
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service-nodeport
  namespace: krypton
spec:
  type: NodePort
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
